@api = http://localhost:5000/api

// New User
POST {{api}}/user/new
Content-Type: application/json

{
    "name": "Admin",
    "email": "admin@admin.org",
    "password": "12345678",
    "createdBy": null 
}
// if someone created this user, just insert at createdBy field your UUID

###

// User Auth
POST {{api}}/user/login
Content-Type: application/json

{
    "email": "admin@admin.org",
    "password": "12345678"
}
